version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-traderplus_db}
      POSTGRES_USER: ${DB_USER:-traderplus_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-traderplus_user}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Go Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - prod.env
    environment:
      PORT: ${PORT:-8080}
      DB_CONNECTION_STRING: postgresql://${DB_USER:-traderplus_user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-traderplus_db}?sslmode=disable
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST:-smtp.mail.ru}
      SMTP_PORT: ${SMTP_PORT:-465}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Frontend with SSL
  frontend:
    build:
      context: ./TradePlusOnline
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local 