#!/bin/bash

# Скрипт для генерации содержимого секрета PROD_ENV_FILE
# Скопируй этот вывод и вставь в GitHub Secrets как PROD_ENV_FILE

echo "=== Содержимое для GitHub Secret: PROD_ENV_FILE ==="
echo ""
echo "# Database Configuration"
echo "DB_USER=traderplus_user"
echo "DB_PASSWORD=0J-zaDcQy9JHH)9WSHbj"
echo "DB_NAME=traderplus_db"
echo "DB_CONNECTION_STRING=postgresql://traderplus_user:0J-zaDcQy9JHH)9WSHbj@db:5432/traderplus_db?sslmode=disable"
echo ""
echo "# Email Configuration"
echo "EMAIL_PASSWORD=Lp4p1f2vQvdwgxmefjND"
echo "EMAIL_ADDRESS=four-x-teams@mail.ru"
echo "SMTP_HOST=smtp.mail.ru"
echo "SMTP_PORT=465"
echo ""
echo "# Server Configuration"
echo "FRONTEND_PORT=80"
echo "PORT=8080"
echo ""
echo "=== Скопируй строки выше (без комментариев) в GitHub Secret ==="
echo ""
echo "После создания секрета PROD_ENV_FILE оставь только SSH секреты:"
echo "- HOST"
echo "- USERNAME"
echo "- SSH_KEY"
echo "- PORT"
echo ""
echo "🚀 Проект теперь использует упрощенную продакшн конфигурацию!" 